directories:
  output: release
  buildResources: build
appId: com.inventory.app
productName: 库存管理系统
files:
  - filter:
      - dist/**/*
      - src/**/*
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
  signAndEditExecutable: false
  artifactName: ${productName}-Setup-${version}.${ext}
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  installerIcon: build/icon.ico
  uninstallerIcon: build/icon.ico
  installerHeaderIcon: build/icon.ico
  artifactName: ${productName}-Setup-${version}.${ext}
asar: true
asarUnpack:
  - '**/*.node'
npmRebuild: false
electronVersion: 25.9.8
